name: musicapi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests with tox
        run: tox


  build-and-push:
    runs-on: ubuntu-latest
    needs: tox
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version tag
        id: get_version
        run: |
          CURRENT_VERSION=$(grep -m 1 '^version =' pyproject.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          LATEST_TAG=$(gh release list --limit 1 | awk '{print $1}' | sed 's/^v//')
          if [ -z "$LATEST_TAG" ]; then LATEST_TAG="0.0.0"; fi
          
          echo "Latest tag: $LATEST_TAG"
          IFS='.' read -ra CUR <<< "$CURRENT_VERSION"
          IFS='.' read -ra LAT <<< "$LATEST_TAG"
          
          IS_NEW_MINOR=false
          if [ "${CUR[1]}" -gt "${LAT[1]}" ] || [ "${CUR[0]}" -gt "${LAT[0]}" ]; then
            IS_NEW_MINOR=true
          fi

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "IS_NEW_MINOR=$IS_NEW_MINOR" >> $GITHUB_OUTPUT
          echo "Current: $CURRENT_VERSION, Latest: $LATEST_TAG, Is New Minor: $IS_NEW_MINOR"
          

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ghcr.io/fsdmu/musicapi:${{ steps.get_version.outputs.VERSION }}

      - name: Log in to GitHub Container Registry
        if: >
          github.event_name == 'push' && 
          github.ref == 'refs/heads/main' && 
          steps.get_version.outputs.IS_NEW_MINOR == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        if: >
          github.event_name == 'push' && 
          github.ref == 'refs/heads/main' && 
          steps.get_version.outputs.IS_NEW_MINOR == 'true'
        run: |
          docker push ghcr.io/fsdmu/musicapi:${{ steps.get_version.outputs.CURRENT_VERSION }}
          docker tag ghcr.io/fsdmu/musicapi:${{ steps.get_version.outputs.CURRENT_VERSION }} ghcr.io/fsdmu/musicapi:latest
          docker push ghcr.io/fsdmu/musicapi:latest

      - name: Create GitHub Release
        if: >
          github.event_name == 'push' && 
          github.ref == 'refs/heads/main' && 
          steps.get_version.outputs.IS_NEW_MINOR == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.CURRENT_VERSION }}
          name: v${{ steps.get_version.outputs.CURRENT_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true